# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'salesforce-bulkapi-notifier', '~> 0.0.1'

group :development do
  gem "guard"
  gem "guard-rspec"
  gem 'pry'
  gem 'byebug'
  gem 'pry-byebug'
  gem 'rspec'
end
